// Segment-glyph face, DATA-DRIVEN: glyph geometry lives in engine-bound uniform
// tables and one small evaluator loop walks the strokes — same lattice, same SDF
// semantics as the old per-glyph functions, but orders of magnitude less CODE (the
// inlined glyph switch made driver shader-codegen explode on register-starved GPUs).
// GENERATED by scripts/gen_glyphs.py — edit the python stroke tables, regenerate;
// do not hand-edit. Glyph-local cell: x in [-0.5,0.5], y in [-1,1].
// Public surface: SB_sd_char. sbt_* names are library-private (not catalogued;
// layout.glsl composes sbt_char_skel).

float sbt_arc(vec2 p, vec2 c, vec2 q) {
    vec2 v = (p - c) / 0.5;
    float dist = abs(length(v) - 1.0) * 0.5;
    float in_q = step(0.0, v.x * q.x) * step(0.0, v.y * q.y);
    vec2 e1 = c + vec2(q.x * 0.5, 0.0);
    vec2 e2 = c + vec2(0.0, q.y * 0.5);
    return mix(min(distance(p, e1), distance(p, e2)), dist, in_q);
}

float sbt_arc_tall(vec2 p, vec2 c, vec2 q) {
    vec2 v = (p - c) / vec2(0.5, 1.0);
    float len = max(length(v), 0.0001);
    // First-order true distance |phi|/|grad phi| (the naive estimate rendered
    // arc-armed glyphs visibly bolder near the vertical endpoints).
    float dist = abs(len - 1.0) * len / max(length(vec2(v.x / 0.5, v.y)), 0.0001);
    float in_q = step(0.0, v.x * q.x) * step(0.0, v.y * q.y);
    vec2 e1 = c + vec2(q.x * 0.5, 0.0);
    vec2 e2 = c + vec2(0.0, q.y * 1.0);
    return mix(min(distance(p, e1), distance(p, e2)), dist, in_q);
}

int sbt_glyph_id(uint cp) {
    if (cp >= 97u && cp <= 122u) cp -= 32u;
    if (cp >= 1072u && cp <= 1103u) cp -= 32u;
    if (cp == 1105u) cp = 1025u;
    if (cp >= 65u && cp <= 90u) return int(cp) - 65;
    if (cp >= 48u && cp <= 57u) return 26 + int(cp) - 48;
    if (cp >= 1040u && cp <= 1071u) return 46 + int(cp) - 1040;
    if (cp == 1025u) return 45;
    if (cp == 33u) return 36;
    if (cp == 38u) return 37;
    if (cp == 39u) return 38;
    if (cp == 44u) return 39;
    if (cp == 45u) return 40;
    if (cp == 46u) return 41;
    if (cp == 58u) return 42;
    if (cp == 59u) return 43;
    if (cp == 63u) return 44;
    return -1;
}

// Tables are ENGINE-BOUND uniform arrays on purpose: a dynamically-indexed
// const array (function-local OR global) is demoted to per-thread local memory
// on NVIDIA (~100x slower text stack); a uniform array lives in the constant
// bank on every driver tested, and keeps V3D codegen small (the original
// inlined glyph switch exploded its compile). Node.compile() writes the values
// from shaderbox/glyph_tables.py — generated together with this file, never
// node-settable (ENGINE_DRIVEN_UNIFORMS). Span per glyph: x = stroke offset,
// y = segment count, z = arc count, w = (tall_arc_count << 8) | dot_count.
// Strokes are pre-sorted by kind.
uniform ivec4 SBT_SPANS[78];
uniform vec4 SBT_STROKES[520];

ivec4 sbt_glyph_span(int g) {
    return SBT_SPANS[g];
}

vec4 sbt_stroke_data(int i) {
    return SBT_STROKES[i];
}

float sbt_char_skel(vec2 p, uint cp) {
    int g = sbt_glyph_id(cp);
    if (g < 0) return 100000.0;
    ivec4 span = sbt_glyph_span(g);
    float d = 100000.0;
    int i = span.x;
    for (int k = 0; k < span.y; ++k) {
        vec4 st = sbt_stroke_data(i++);
        d = min(d, SB_sd_segment(p, st.xy, st.zw));
    }
    for (int k = 0; k < span.z; ++k) {
        vec4 st = sbt_stroke_data(i++);
        d = min(d, sbt_arc(p, st.xy, st.zw));
    }
    for (int k = 0; k < (span.w >> 8); ++k) {
        vec4 st = sbt_stroke_data(i++);
        d = min(d, sbt_arc_tall(p, st.xy, st.zw));
    }
    for (int k = 0; k < (span.w & 0xFF); ++k) {
        vec4 st = sbt_stroke_data(i++);
        d = min(d, distance(p, st.xy) - st.z);
    }
    return d;
}

/// SIGNED distance (negative inside the ink) to one glyph in glyph-local coords
/// (cell x in [-0.5,0.5], y in [-1,1]). `weight` = stroke half-width in the same
/// LOCAL units (0.1 regular .. 0.25 bold). To place a glyph of height ch at uv
/// position c: SB_sd_char((uv - c) / (0.5*ch), cp, 0.1) * (0.5*ch) — the *0.5*ch
/// converts the result back to uv units. Lowercase folds to uppercase; supports
/// A-Z, Cyrillic А-Я/Ё, 0-9 and ! ? : ; , . - ' &. Unknown codepoints draw nothing.
float SB_sd_char(vec2 p, uint codepoint, float weight) {
    return sbt_char_skel(p, codepoint) - weight;
}
