services:
  litestar-api:
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ${HOME}/.local/share/shaderbox:/root/.local/share/shaderbox
    command: ["uv", "run", "uvicorn", "shaderbox.app:app", "--host", "0.0.0.0", "--port", "8229"]
