[project]
name = "shaderbox"
version = "0.1.0"
authors = [
    { name = "Alexey Karnachev", email = "alekseykarnachev@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "crossfiledialog>=1.0.0",
    "glfw>=2.8.0",
    "imageio[ffmpeg]>=2.37.0",
    "imgui[glfw]>=2.0.0",
    "loguru>=0.7.3",
    "moderngl>=5.12.0",
    "numpy>=2.2.4",
    "pillow>=11.1.0",
    "pyimgui-stubs>=0.0.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["shaderbox"]

[tool.uv]
dev-dependencies = [ ]

